// src/pages/ProblemDetail.jsx
import { useState, useCallback, useMemo } from 'react'
import { useParams, Link, useNavigate } from 'react-router-dom'
import { problems } from '../data/problems'
import { judge } from '../utils/judge'
import { addSubmission, getSubmissions } from '../utils/storage'
import ProblemRenderer from '../components/ProblemRenderer'
import CodeEditor from '../components/CodeEditor'

export default function ProblemDetail() {
  const { problemId } = useParams()
  const navigate = useNavigate()
  const problem = problems.find((p) => p.id === problemId)

  const lastSub = useMemo(() => {
    const subs = getSubmissions()
    for (const s of subs) {
      if (s.problemId === problemId) return s
    }
    return null
  }, [problemId])

  const [code, setCode] = useState(lastSub ? lastSub.code : '')
  const [language, setLanguage] = useState(lastSub ? lastSub.language : 'cpp')
  const [submitting, setSubmitting] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleCopy = useCallback(async () => {
    if (!problem) return
    try {
      await navigator.clipboard.writeText(problem.description)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = problem.description
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }, [problem])

  const handleSubmit = () => {
    if (!code.trim() || submitting || !problem) return
    setSubmitting(true)

    const judgeResult = judge(code, problem, language)

    const submission = addSubmission({
      problemId: problem.id,
      problemTitle: problem.title,
      code,
      language,
      status: judgeResult.status,
      similarity: judgeResult.similarity,
      output: judgeResult.output,
      testResults: judgeResult.testResults,
      passedTests: judgeResult.passedTests,
      totalTests: judgeResult.totalTests,
    })

    navigate(`/record/${submission.id}`)
  }

  if (!problem) {
    return (
      <div className="page-container">
        <div className="not-found">
          <i className="fas fa-question-circle"></i>
          <h2>题目不存在</h2>
          <Link to="/problems" className="btn-back">
            <i className="fas fa-arrow-left"></i>
            返回题目列表
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="page-container problem-detail-page">
      <div className="problem-header">
        <div className="problem-meta">
          <h2>
            <span className="problem-id">{problem.id}</span>
            {problem.title}
          </h2>
          <span className={`tag ${
            problem.difficulty === '简单' ? 'tag-easy' :
            problem.difficulty === '中等' ? 'tag-medium' : 'tag-hard'
          }`}>
            {problem.difficulty}
          </span>
        </div>
        <button className="btn-copy" onClick={handleCopy}>
          <i className={`fas fa-${copied ? 'check' : 'clipboard'}`}></i>
          {copied ? '已复制' : '复制题目'}
        </button>
      </div>

      <div className="problem-layout">
        <div className="problem-left">
          <ProblemRenderer description={problem.description} />
        </div>
        <div className="problem-right">
          <CodeEditor
            value={code}
            onChange={setCode}
            language={language}
            onLanguageChange={setLanguage}
          />
          <button
            className="btn-submit"
            onClick={handleSubmit}
            disabled={!code.trim() || submitting}
          >
            {submitting ? (
              <><i className="fas fa-spinner fa-spin"></i> 评测中...</>
            ) : (
              <><i className="fas fa-paper-plane"></i> 提交评测</>
            )}
          </button>
        </div>
      </div>
    </div>
  )
}

// src/pages/ProblemDetail.vue
<script setup>
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { addSubmission } from '../utils/storage'
import { startJudge } from '../utils/judgeManager'
import { useProblems } from '../composables/useProblems'
import { useSubmissions } from '../composables/useSubmissions'
import { useClipboard } from '../composables/useClipboard'
import ProblemRenderer from '../components/ProblemRenderer.vue'
import CodeEditor from '../components/CodeEditor.vue'

const route = useRoute()
const router = useRouter()
const { getById } = useProblems()
const { latestForProblem } = useSubmissions(computed(() => route.params.problemId))
const { copied, copy } = useClipboard()
const problem = computed(() => getById(route.params.problemId))
const code = ref('')
const language = ref('cpp')
let loadedProblemId

const loadLastSubmission = () => {
  if (loadedProblemId === route.params.problemId) return
  loadedProblemId = route.params.problemId
  code.value = latestForProblem.value?.code || ''
  language.value = latestForProblem.value?.language || 'cpp'
}
loadLastSubmission()
watch(() => route.params.problemId, loadLastSubmission)

async function submit() {
  const currentProblem = problem.value
  if (!code.value.trim() || !currentProblem) return
  const submission = addSubmission({ problemId: currentProblem.id, problemTitle: currentProblem.title, code: code.value, language: language.value, status: 'running', timeLimit: currentProblem.timeLimit, testResults: currentProblem.testCases.map((testCase) => ({ input: testCase.input, expected: testCase.output, actual: null, passed: false, status: 'pending', durationMs: null })), passedTests: 0, totalTests: currentProblem.testCases.length })
  await router.push(`/record/${submission.id}`)
  void startJudge(submission, currentProblem)
}
</script>

<template>
  <div v-if="!problem" class="page-container"><div class="not-found"><i class="fas fa-question-circle" /><h2>题目不存在</h2><RouterLink to="/problems" class="btn-back"><i class="fas fa-arrow-left" />返回题目列表</RouterLink></div></div>
  <div v-else class="page-container problem-detail-page">
    <div class="problem-header"><div class="problem-meta"><h2><span class="problem-id">{{ problem.id }}</span>{{ problem.title }}</h2><span :class="['tag', problem.difficulty === '简单' ? 'tag-easy' : problem.difficulty === '中等' ? 'tag-medium' : 'tag-hard']">{{ problem.difficulty }}</span><span class="problem-time-limit"><i class="fas fa-stopwatch" />{{ problem.timeLimit }} ms / 测试点</span></div><button class="btn-copy" @click="copy(problem.description)"><i :class="['fas', copied ? 'fa-check' : 'fa-clipboard']" />{{ copied ? '已复制' : '复制题目' }}</button></div>
    <div class="problem-layout"><div class="problem-left"><ProblemRenderer :description="problem.description" /></div><div class="problem-right"><CodeEditor :value="code" :language="language" @update:value="code = $event" @update:language="language = $event" /><button class="btn-submit" :disabled="!code.trim()" @click="submit"><i class="fas fa-paper-plane" />提交评测</button></div></div>
  </div>
</template>
