// src/pages/RecordDetail.jsx
import { useParams, Link } from 'react-router-dom'
import { getSubmission, getSubmissions } from '../utils/storage'

function formatTime(ts) {
  const d = new Date(ts)
  const pad = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
}

function formatDuration(durationMs) {
  if (typeof durationMs !== 'number') return '-'
  if (durationMs < 1) return '<1 ms'
  return `${durationMs.toFixed(2)} ms`
}

function displayStatus(sub) {
  if (sub.status === 'ac') {
    return { icon: 'check-circle', label: '通过', color: '#52c41a' }
  }
  return { icon: 'times-circle', label: '未通过', color: '#faad14' }
}

function getPrevNext(id) {
  const subs = getSubmissions()
  const idx = subs.findIndex((s) => s.id === id)
  if (idx === -1) return {}
  return {
    prev: idx < subs.length - 1 ? subs[idx + 1] : null,
    next: idx > 0 ? subs[idx - 1] : null,
  }
}

export default function RecordDetail() {
  const { recordId } = useParams()
  const sub = getSubmission(recordId)
  const { prev, next } = getPrevNext(recordId)

  if (!sub) {
    return (
      <div className="page-container">
        <div className="not-found">
          <i className="fas fa-question-circle"></i>
          <h2>提交记录不存在</h2>
          <Link to="/record" className="btn-back">
            <i className="fas fa-arrow-left"></i>
            返回评测记录
          </Link>
        </div>
      </div>
    )
  }

  const cfg = displayStatus(sub)

  return (
    <div className="page-container">
      <div className="page-header">
        <h2>
          <Link to="/record" className="header-back-link">
            <i className="fas fa-arrow-left"></i>
          </Link>
          评测详情
        </h2>
        <span className="detail-id-label">#{sub.id}</span>
      </div>

      <div className="submission-detail">
        <div className="detail-header">
          <h3>
            <i className={`fas fa-${cfg.icon}`} style={{ color: cfg.color }}></i>
            {cfg.label}
          </h3>
          <span className="detail-time">{formatTime(sub.timestamp)}</span>
        </div>

        <div className="detail-meta">
          <span>
            <i className="fas fa-book"></i>
            题目: <Link to={`/problem/${sub.problemId}`}>{sub.problemId} {sub.problemTitle}</Link>
          </span>
          <span>
            <i className="fas fa-code"></i>
            语言: {sub.language}
          </span>
          <span>
            <i className={`fas fa-${cfg.icon}`} style={{ color: cfg.color }}></i>
            状态: {cfg.label}
          </span>
          {sub.similarity !== undefined && sub.similarity < 0.5 && sub.similarity > 0 && (
            <span>
              <i className="fas fa-chart-line"></i>
              相似度: {(sub.similarity * 100).toFixed(0)}%
            </span>
          )}
        </div>

        {sub.totalTests !== undefined && (
          <div className="detail-summary">
            <i className={`fas fa-${sub.status === 'ac' ? 'check-circle' : 'times-circle'}`} style={{ color: sub.status === 'ac' ? '#52c41a' : '#faad14' }}></i>
            通过 <strong>{sub.passedTests}</strong> / {sub.totalTests} 个测试点
          </div>
        )}

        {sub.testResults && sub.testResults.length > 0 && (
          <div className="detail-tc-table-wrap">
            {sub.testResults.map((tc, i) => (
              <details key={i} className={`tc-item ${tc.passed ? 'tc-passed' : 'tc-failed'}`}>
                <summary className="tc-summary">
                  <span className="tc-summary-title">测试点 {i + 1}</span>
                  <span className="tc-summary-time">
                    <i className="fas fa-stopwatch"></i>
                    {formatDuration(tc.durationMs)}
                  </span>
                  <span className={tc.passed ? 'tc-ok' : tc.error ? 'tc-err' : 'tc-no'}>
                    <i className={`fas fa-${tc.passed ? 'check-circle' : tc.error ? 'exclamation-circle' : 'times-circle'}`}></i>
                    {tc.passed ? '通过' : tc.error ? '运行错误' : '未通过'}
                  </span>
                  <i className="fas fa-chevron-down tc-expand-icon"></i>
                </summary>
                <div className="tc-content">
                  <div className="tc-output-block">
                    <span className="tc-output-label">输入</span>
                    <pre><code>{tc.input || '(空)'}</code></pre>
                  </div>
                  <div className="tc-output-block">
                    <span className="tc-output-label">标准输出</span>
                    <pre><code>{tc.expected || '(空)'}</code></pre>
                  </div>
                  <div className="tc-output-block">
                    <span className="tc-output-label">你的程序输出</span>
                    <pre><code>{tc.actual || '(空)'}</code></pre>
                  </div>
                </div>
              </details>
            ))}
          </div>
        )}

        {sub.output && sub.status !== 'ac' && !sub.testResults && (
          <div className="detail-output">
            <div className="detail-output-header">
              <i className="fas fa-terminal"></i>
              {sub.similarity === 0 && (sub.output.includes('Error') || sub.output.includes('error') || sub.output.includes('Expected')) ? '编译/运行错误' : '程序输出'}
            </div>
            <pre className="detail-output-content"><code>{sub.output}</code></pre>
          </div>
        )}

        <div className="detail-code">
          <div className="detail-code-header">
            <i className="fas fa-file-code"></i>
            提交代码
          </div>
          <pre><code>{sub.code}</code></pre>
        </div>
      </div>

      <div className="detail-nav">
        {prev ? (
          <Link to={`/record/${prev.id}`} className="detail-nav-link prev">
            <i className="fas fa-chevron-left"></i>
            上一条
          </Link>
        ) : <span />}
        {next ? (
          <Link to={`/record/${next.id}`} className="detail-nav-link next">
            下一条
            <i className="fas fa-chevron-right"></i>
          </Link>
        ) : <span />}
      </div>
    </div>
  )
}

// src/pages/RecordDetail.vue
<script setup>
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useSubmissions } from '../composables/useSubmissions'

const route = useRoute()
const router = useRouter()
const { getById } = useSubmissions()
const sub = computed(() => getById(route.params.recordId))
const formatTime = (ts) => { const d = new Date(ts); const pad = (n) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}` }
const formatDuration = (ms) => typeof ms !== 'number' ? '-' : ms < 1 ? '<1 ms' : `${ms.toFixed(2)} ms`
const statusConfig = (status) => ({ running: ['fa-spinner fa-spin', '评测中', '#1677ff'], tle: ['fa-clock', '运行超时', '#f5222d'], error: ['fa-exclamation-circle', '运行错误', '#f5222d'], ac: ['fa-check-circle', '通过', '#52c41a'] }[status] || ['fa-times-circle', '未通过', '#faad14'])
const testConfig = (tc) => { const status = tc.status || (tc.passed ? 'passed' : 'failed'); return { statusClass: status === 'running' ? 'tc-running' : ['skipped', 'pending'].includes(status) ? 'tc-pending' : tc.passed ? 'tc-ok' : tc.error ? 'tc-err' : 'tc-no', icon: status === 'running' ? 'fa-spinner fa-spin' : tc.passed ? 'fa-check-circle' : tc.error ? 'fa-exclamation-circle' : status === 'timeout' ? 'fa-clock' : status === 'skipped' ? 'fa-forward' : 'fa-times-circle', label: status === 'running' ? '运行中' : status === 'pending' ? '等待中' : status === 'skipped' ? '已跳过' : tc.passed ? '通过' : status === 'timeout' ? '超时' : tc.error ? '运行错误' : '未通过' } }
const goBack = () => router.back()
</script>

<template>
  <div v-if="!sub" class="page-container"><div class="not-found"><i class="fas fa-question-circle" /><h2>提交记录不存在</h2><button type="button" class="btn-back" @click="goBack"><i class="fas fa-arrow-left" />返回</button></div></div>
  <div v-else class="page-container"><div class="page-header"><h2><button type="button" class="header-back-link" aria-label="返回上一页" @click="goBack"><i class="fas fa-arrow-left" /></button>评测详情</h2><span class="detail-id-label">#{{ sub.id }}</span></div>
    <div class="submission-detail"><div class="detail-header"><h3><i :class="['fas', ...statusConfig(sub.status)[0].split(' ')]" :style="{ color: statusConfig(sub.status)[2] }" />{{ statusConfig(sub.status)[1] }}</h3><span class="detail-time">{{ formatTime(sub.timestamp) }}</span></div>
      <div class="detail-meta"><span><i class="fas fa-book" />题目: <RouterLink :to="`/problem/${sub.problemId}`">{{ sub.problemId }} {{ sub.problemTitle }}</RouterLink></span><span><i class="fas fa-code" />语言: {{ sub.language }}</span><span v-if="sub.timeLimit !== undefined"><i class="fas fa-stopwatch" />时间限制: {{ sub.timeLimit }} ms / 测试点</span><span><i :class="['fas', ...statusConfig(sub.status)[0].split(' ')]" :style="{ color: statusConfig(sub.status)[2] }" />状态: {{ statusConfig(sub.status)[1] }}</span><span v-if="sub.similarity !== undefined && sub.similarity < .5 && sub.similarity > 0"><i class="fas fa-chart-line" />相似度: {{ (sub.similarity * 100).toFixed(0) }}%</span></div>
      <div v-if="sub.totalTests !== undefined" class="detail-summary"><i :class="['fas', sub.status === 'running' ? 'fa-spinner fa-spin' : sub.status === 'ac' ? 'fa-check-circle' : sub.status === 'tle' ? 'fa-clock' : 'fa-times-circle']" :style="{ color: statusConfig(sub.status)[2] }" />已通过 <strong>{{ sub.passedTests }}</strong> / {{ sub.totalTests }} 个测试点</div>
      <div v-if="sub.testResults?.length" class="detail-tc-table-wrap"><details v-for="(tc, index) in sub.testResults" :key="index" :class="['tc-item', `tc-${tc.status || (tc.passed ? 'passed' : 'failed')}`]"><summary class="tc-summary"><span class="tc-summary-title">测试点 {{ index + 1 }}</span><span class="tc-summary-time"><i class="fas fa-stopwatch" />{{ formatDuration(tc.durationMs) }}</span><span :class="testConfig(tc).statusClass"><i :class="['fas', ...testConfig(tc).icon.split(' ')]" />{{ testConfig(tc).label }}</span><i class="fas fa-chevron-down tc-expand-icon" /></summary><div class="tc-content"><div v-for="item in [['输入', tc.input || '(空)'], ['标准输出', tc.expected || '(空)'], ['你的程序输出', tc.actual || (tc.status === 'skipped' ? '未运行' : '(空)')]]" :key="item[0]" class="tc-output-block"><span class="tc-output-label">{{ item[0] }}</span><pre><code>{{ item[1] }}</code></pre></div></div></details></div>
      <div v-if="sub.output && sub.status !== 'ac' && !sub.testResults" class="detail-output"><div class="detail-output-header"><i class="fas fa-terminal" />程序输出</div><pre class="detail-output-content"><code>{{ sub.output }}</code></pre></div>
      <div class="detail-code"><div class="detail-code-header"><i class="fas fa-file-code" />提交代码</div><pre><code>{{ sub.code }}</code></pre></div>
    </div>
  </div>
</template>
