// src/components/Navbar.jsx
import { NavLink, Link } from 'react-router-dom'
import { getNickname, clearNickname } from '../utils/storage'

export default function Navbar({ onLogout }) {
  const nickname = getNickname()

  const handleLogout = () => {
    clearNickname()
    if (onLogout) onLogout()
  }

  return (
    <nav className="navbar">
      <div className="navbar-inner">
        <div className="navbar-left">
          <NavLink to="/problems" className="navbar-brand">
            <i className="fas fa-code"></i>
            <span>Browser OJ</span>
          </NavLink>
          <div className="navbar-links">
            <NavLink to="/problems" className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>
              <i className="fas fa-list"></i>
              题目
            </NavLink>
            <NavLink to="/record" className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>
              <i className="fas fa-history"></i>
              评测记录
            </NavLink>
          </div>
        </div>
        <div className="navbar-right">
          {nickname && (
            <>
              <span className="navbar-user">
                <i className="fas fa-user-circle"></i>
                {nickname}
              </span>
              <button className="btn-logout" onClick={handleLogout} title="退出">
                <i className="fas fa-sign-out-alt"></i>
              </button>
            </>
          )}
          {!nickname && (
            <Link to="/login" className="navbar-login">
              <i className="fas fa-sign-in-alt"></i>
              登录
            </Link>
          )}
        </div>
      </div>
    </nav>
  )
}

// src/components/Navbar.vue
<script setup>
import { useAuth } from '../composables/useAuth'

defineEmits(['logout'])
const { nickname, avatarUrl } = useAuth()
</script>

<template>
  <nav class="topbar">
    <div class="topbar-brand">
      <RouterLink to="/problems" class="navbar-brand"><i class="fas fa-code" /><span>Browser OJ</span></RouterLink>
      <span class="topbar-title">在线评测系统</span>
    </div>
    <div class="topbar-right">
      <div class="navbar-right">
        <template v-if="nickname">
          <span class="navbar-user">
            <img v-if="avatarUrl" class="navbar-avatar" :src="avatarUrl" :alt="`${nickname} 的头像`" @error="$event.target.style.display = 'none'">
            <i v-else class="fas fa-user-circle" />
            {{ nickname }}
          </span>
          <button class="btn-logout" title="退出" @click="$emit('logout')"><i class="fas fa-sign-out-alt" /></button>
        </template>
        <RouterLink v-else to="/login" class="navbar-login"><i class="fas fa-sign-in-alt" />登录</RouterLink>
      </div>
    </div>
  </nav>
  <aside class="sidebar">
    <nav class="sidebar-nav" aria-label="主导航">
      <RouterLink to="/problems" class="nav-link"><i class="fas fa-list" /><span>题目</span></RouterLink>
      <RouterLink to="/record" class="nav-link"><i class="fas fa-history" /><span>评测记录</span></RouterLink>
    </nav>
  </aside>
</template>
